import type { ICUToken } from '../src'
import { ICUUtil } from '../src'

type ExampleValues = {
  name: string,
  message: string,
  result: ICUToken[],
}

const examples: ExampleValues[] = [
  {
    name: 'Simple Replace',
    message: 'Hello {name}',
    result: [
      { type: 'TEXT', value: 'Hello' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'name' },
      { type: 'RBRACE' }
    ],
  },
  {
    name: 'Plural with number insertion',
    message: 'You have {count, plural, =1{# apple} other{# apples}}',
    result: [
      { type: 'TEXT', value: 'You' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'have' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'count' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'plural' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '=1' },
      { type: 'LBRACE' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'apple' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'apples' },
      { type: 'RBRACE' },
      { type: 'RBRACE' }
    ],
  },
  {
    name: 'Select with nested replacement',
    message: '{gender, select, male{Hello Mr. {name}} female{Hello Ms. {name}} other{Hello {name}}}',
    result: [
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'gender' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'select' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'male' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Hello' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'Mr.' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'name' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'female' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Hello' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'Ms.' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'name' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Hello' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'name' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'RBRACE' }
    ],
  },
  {
    name: 'Plural and Select in succession',
    message: '{count, plural, =0{no items} =1{one item} other{# items}} and {gender, select, male{sir} other{friend}}',
    result: [
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'count' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'plural' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '=0' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'no' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'items' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '=1' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'one' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'item' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'items' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'and' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'gender' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'select' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'male' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'sir' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'friend' },
      { type: 'RBRACE' },
      { type: 'RBRACE' }
    ],
  },
  {
    name: 'Plural nested in Select',
    message: '{userType, select, admin{{count, plural, =1{Admin, 1 message} other{Admin, # messages}}} member{{count, plural, =1{Member, 1 message} other{Member, # messages}}} other{Guest}}',
    result: [
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'userType' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'select' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'admin' },
      { type: 'LBRACE' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'count' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'plural' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '=1' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Admin' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '1' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'message' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Admin' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'messages' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'member' },
      { type: 'LBRACE' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'count' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'plural' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '=1' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Member' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '1' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'message' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Member' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'messages' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'Guest' },
      { type: 'RBRACE' },
      { type: 'RBRACE' }
    ],
  },
  {
    name: 'Replace, Escape and Plural',
    message: "Today is '{'special'}' and you have {count, plural, =1{# cat} other{# cats}}",
    result: [
      { type: 'TEXT', value: 'Today' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'is' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'ESCAPE' },
      { type: 'LBRACE' },
      { type: 'ESCAPE' },
      { type: 'TEXT', value: 'special' },
      { type: 'ESCAPE' },
      { type: 'RBRACE' },
      { type: 'ESCAPE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'and' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'you' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'have' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'LBRACE' },
      { type: 'TEXT', value: 'count' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'plural' },
      { type: 'COMMA' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: '=1' },
      { type: 'LBRACE' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'cat' },
      { type: 'RBRACE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'other' },
      { type: 'LBRACE' },
      { type: 'HASHTAG' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'TEXT', value: 'cats' },
      { type: 'RBRACE' },
      { type: 'RBRACE' }
    ],
  },
  {
    name: 'Escape sequence',
    message: "'''''' '{}'",
    result: [
      { type: 'ESCAPE' },
      { type: 'ESCAPE' },
      { type: 'ESCAPE' },
      { type: 'ESCAPE' },
      { type: 'ESCAPE' },
      { type: 'ESCAPE' },
      { type: 'WHITESPACE', value: ' ' },
      { type: 'ESCAPE' },
      { type: 'LBRACE' },
      { type: 'RBRACE' },
      { type: 'ESCAPE' },
    ],
  }
]

describe('ICU Lexer', () => {
  for (const example of examples) {
    test(`${example.name}: ${example.message}`, () => {
      const result = ICUUtil.lex(example.message)
      expect(result).toEqual(example.result)
    })
  }
})